/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.view;

import br.com.etec.model.Login;
import br.com.etec.util.Utils;
import java.awt.event.KeyEvent;
import javax.swing.JButton;
import org.springframework.stereotype.Component;

/**
 * Tela principal da aplicação. Realiza o acesso ao sistema.
 *
 * <p>
 *  <code>LoginView</code> é mapeada como <code>@Component</code> do Spring.
 *  Dessa forma uma instância de <code>ListaMercadoriasFrame</code> pode ser criada e gerenciada
 *  pelo Spring, favorecendo a Inversão de Controle <i>(IoC)</i> e Injeção de Dependência <i>(DI)</i>.
 * </p>
 *
 * @author Diego Felix
 */
@Component
public class LoginView extends javax.swing.JDialog {

    /**
     * Creates new form LoginView
     */
    public LoginView() {
        super();
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        loginBean = new br.com.etec.model.Login();
        jPanel1 = new javax.swing.JPanel();
        lblLogoCTPS = new javax.swing.JLabel();
        lblLogoETEC = new javax.swing.JLabel();
        panelCampos = new javax.swing.JPanel();
        lblUsuario = new javax.swing.JLabel();
        lblSenha = new javax.swing.JLabel();
        txtUsuario = new javax.swing.JTextField();
        pwdSenha = new javax.swing.JPasswordField();
        btnOk = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/com/etec/view/Bundle"); // NOI18N
        setTitle(bundle.getString("LoginView.title")); // NOI18N
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        setIconImage(Utils.getDefaultImage());
        setModal(true);
        setName("Form"); // NOI18N
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setName("panelTela"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblLogoCTPS.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_ctps.png"))); // NOI18N
        lblLogoCTPS.setText(bundle.getString("LoginView.lblLogoCTPS.text")); // NOI18N
        lblLogoCTPS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblLogoCTPS.setName("lblLogoCTPS"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 3, 20);
        jPanel1.add(lblLogoCTPS, gridBagConstraints);

        lblLogoETEC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo_eteab.png"))); // NOI18N
        lblLogoETEC.setText(bundle.getString("LoginView.lblLogoETEC.text")); // NOI18N
        lblLogoETEC.setName("lblLogoETEC"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(3, 0, 10, 0);
        jPanel1.add(lblLogoETEC, gridBagConstraints);

        panelCampos.setBackground(new java.awt.Color(255, 255, 255));
        panelCampos.setBorder(javax.swing.BorderFactory.createTitledBorder(null, bundle.getString("LoginView.panelCampos.border.title"), javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 10), new java.awt.Color(204, 204, 204))); // NOI18N
        panelCampos.setFont(new java.awt.Font("Arial", 0, 10)); // NOI18N
        panelCampos.setName("panelCampos"); // NOI18N
        panelCampos.setLayout(new java.awt.GridBagLayout());

        lblUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblUsuario.setText(bundle.getString("LoginView.lblUsuario.text")); // NOI18N
        lblUsuario.setName("lblUsuario"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(15, 16, 0, 0);
        panelCampos.add(lblUsuario, gridBagConstraints);

        lblSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSenha.setText(bundle.getString("LoginView.lblSenha.text")); // NOI18N
        lblSenha.setName("lblSenha"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(14, 24, 0, 0);
        panelCampos.add(lblSenha, gridBagConstraints);

        txtUsuario.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txtUsuario.setName("txtUsuario"); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, loginBean, org.jdesktop.beansbinding.ELProperty.create("${usuario}"), txtUsuario, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.WEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 18, 0, 16);
        panelCampos.add(txtUsuario, gridBagConstraints);

        pwdSenha.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        pwdSenha.setName("pwdSenha"); // NOI18N

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, loginBean, org.jdesktop.beansbinding.ELProperty.create("${senha}"), pwdSenha, org.jdesktop.beansbinding.BeanProperty.create("text"));
        bindingGroup.addBinding(binding);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.VERTICAL;
        gridBagConstraints.ipadx = 130;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(11, 18, 0, 16);
        panelCampos.add(pwdSenha, gridBagConstraints);

        btnOk.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnOk.setMnemonic(KeyEvent.VK_K);
        btnOk.setText(bundle.getString("LoginView.btnOk.text")); // NOI18N
        btnOk.setActionCommand(bundle.getString("LoginView.btnOk.actionCommand")); // NOI18N
        btnOk.setName("btnOk"); // NOI18N
        btnOk.setPreferredSize(new java.awt.Dimension(83, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 3);
        panelCampos.add(btnOk, gridBagConstraints);

        btnCancelar.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnCancelar.setMnemonic(KeyEvent.VK_C);
        btnCancelar.setText(bundle.getString("LoginView.btnCancelar.text")); // NOI18N
        btnCancelar.setActionCommand(bundle.getString("LoginView.btnCancelar.actionCommand")); // NOI18N
        btnCancelar.setName("btnCancelar"); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipadx = 20;
        gridBagConstraints.ipady = 5;
        gridBagConstraints.insets = new java.awt.Insets(10, 3, 10, 10);
        panelCampos.add(btnCancelar, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(2, 20, 2, 20);
        jPanel1.add(panelCampos, gridBagConstraints);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        bindingGroup.bind();

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-529)/2, (screenSize.height-390)/2, 529, 390);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnOk;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLogoCTPS;
    private javax.swing.JLabel lblLogoETEC;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblUsuario;
    private br.com.etec.model.Login loginBean;
    private javax.swing.JPanel panelCampos;
    private javax.swing.JPasswordField pwdSenha;
    private javax.swing.JTextField txtUsuario;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    public JButton getBtnCancelar() {
        return btnCancelar;
    }

    public JButton getBtnOk() {
        return btnOk;
    }

    public Login getLogin(){
        return loginBean;
    }
}
